### ISSUE TITLE
Doesn't work with GIF

### ISSUE THREAD

**Issue by NatoBoram** [foss-project/green-recorder#141]
1. Select GIF format
2. Select an area
3. Disable audio
4. Click :record_button:
5. Click :stop_button:

The app will notify that the "GIF is currently being processed"... but nothing happens. The default format MKV works fine.

```yaml
OS: Ubuntu 19.04 x86_64 
Host: 3306A4F ThinkCentre M82 
Kernel: 5.0.0-20-generic 
Shell: bash 5.0.3 
Resolution: 1680x1050, 1920x1080 
DE: GNOME 3.32.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
CPU: Intel i5-3470 (4) @ 3.600GHz 
GPU: Intel HD Graphics 
Memory: 6948MiB / 15829MiB 
```

Green Recorder `3.2.3`
